CREATE TABLE "USERS" 
( 
    "USERNAME" VARCHAR2(255 CHAR) NOT NULL, 
    "PASSWORD" VARCHAR2(255 CHAR) NOT NULL,
    "ENABLED" BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY ("USERNAME")
);

CREATE TABLE "AUTHORITIES" (
	"USERNAME" VARCHAR2(255 CHAR) NOT NULL,
	"AUTHORITY" VARCHAR2(255 CHAR) NOT NULL,
	CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);

CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (USERNAME,AUTHORITY);

-- admin/admin@123 using BCryptPasswordEncoder().encode()
insert into users(username,password,enabled)
	values('admin','$2a$10$hbxecwitQQ.dDT4JOFzQAulNySFwEpaFLw38jda6Td.Y/cOiRzDFu',true);

insert into authorities(username,authority) 
	values('admin','ROLE_ADMIN');
